export const ADD_COMMENT="ADD_COMMENT"
export const LOAD_DISHES='LOAD_DISHES'
export const LOAD_COMMENTS='LOAD_COMMENTS'
export const COMMENT_LOADING='COMMENT_LOADING'
export const DISH_LOADING_FAILED="DISH_LOADING_FAILED"
export const DISHES_LOADING='DISHES_LOADING'